spring:
  datasource:
    url: jdbc:postgresql://localhost/turing
    username: postgres
    password: 143286

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate